version: "3.7"
services:
  web:
    container_name: paymentSubSystemService
    build:
      dockerfile: Dockerfile.dev
      context: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/server
    environment:
      JWT_SECRET: JwtSecretTokenWillBeHere
      JWT_EXPIRATION: 8h
      ACCESS_TOKEN_EXPIRATION: 120h
      HOST: db
      PORT: 3000
      USER_NAME: root
      PASSWORD: root
      DATABASE: payment

  # Database
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    volumes:
        - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: payment
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root